sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"

os:
  - linux
  - osx

install:
  - npm install
  - npm i -g typescript jest
  - lerna bootstrap --no-ci

script: npm run test

branches:
  only:
    - master
    - openapi-to-graphql
