sudo: false
language: node_js
node_js:
  - "10"
  - "12"

os:
  - linux
  - osx

install:
  - npm install
  - npm i -g typescript jest
  - lerna bootstrap --ci

script: npm run test

branches:
  only:
    - master
